import { Task, TimeLog, CustomStatus, NotionStatusMapping } from './types';

// Generate deterministic UUIDs for consistency
const id = (n: number) => `00000000-0000-0000-0000-${String(n).padStart(12, '0')}`;

const today = new Date();
const daysAgo = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString();
};
const hoursAgo = (n: number) => {
  const d = new Date(today);
  d.setHours(d.getHours() - n);
  return d.toISOString();
};

export const MOCK_TASKS: Task[] = [
  {
    id: id(1),
    title: '메인 대시보드 API 성능 최적화',
    description: '대시보드 로딩 시간이 3초 이상 걸리는 이슈. 쿼리 최적화 및 캐싱 적용 필요.',
    priority: '긴급',
    status: '진행중',
    source: 'manual',
    requester: null,
    requested_at: null,
    created_at: daysAgo(0),
    deadline: daysAgo(-2), // 2 days from now
    started_at: hoursAgo(6),
    completed_at: null,
    actual_duration: 90,
    is_duration_manual: false,
    notion_task_id: null,
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: null,
    follow_up_note: null,
    is_deleted: false,
  },
  {
    id: id(2),
    title: '신규 회원가입 플로우 디자인 리뷰',
    description: '디자인팀에서 전달한 회원가입 플로우 Figma 시안 리뷰. UX 피드백 정리 후 공유.',
    priority: '높음',
    status: '대기',
    source: 'notion',
    requester: '김민지',
    requested_at: daysAgo(1),
    created_at: daysAgo(1),
    deadline: daysAgo(-1),
    started_at: null,
    completed_at: null,
    actual_duration: null,
    is_duration_manual: false,
    notion_task_id: 'notion-page-001',
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: null,
    follow_up_note: null,
    is_deleted: false,
  },
  {
    id: id(3),
    title: '주간 스프린트 회의록 작성',
    description: '이번 주 스프린트 진행 상황 정리 및 다음 주 계획 수립.',
    priority: '보통',
    status: '완료',
    source: 'manual',
    requester: null,
    requested_at: null,
    created_at: daysAgo(0),
    deadline: null,
    started_at: daysAgo(0),
    completed_at: hoursAgo(1),
    actual_duration: 45,
    is_duration_manual: false,
    notion_task_id: null,
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: null,
    follow_up_note: null,
    is_deleted: false,
  },
  {
    id: id(4),
    title: '결제 모듈 에러 로그 분석',
    description: '오전에 발생한 결제 실패 건 원인 분석. Sentry 로그 확인.',
    priority: '긴급',
    status: '완료',
    source: 'slack',
    requester: '박서준',
    requested_at: daysAgo(0),
    created_at: daysAgo(0),
    deadline: daysAgo(0),
    started_at: hoursAgo(5),
    completed_at: hoursAgo(3),
    actual_duration: 120,
    is_duration_manual: false,
    notion_task_id: null,
    slack_url: 'https://slack.com/archives/C01234/p1234567890',
    notion_issue: null,
    slack_channel: 'dev-alerts',
    slack_sender: '박서준',
    delegate_to: null,
    follow_up_note: '모니터링 대시보드에 알림 추가 필요',
    is_deleted: false,
  },
  {
    id: id(5),
    title: 'CI/CD 파이프라인 Docker 이미지 경량화',
    description: '빌드 시간 단축을 위한 멀티스테이지 빌드 적용.',
    priority: '보통',
    status: '위임',
    source: 'manual',
    requester: null,
    requested_at: null,
    created_at: daysAgo(2),
    deadline: daysAgo(-5),
    started_at: daysAgo(2),
    completed_at: null,
    actual_duration: 30,
    is_duration_manual: true,
    notion_task_id: null,
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: '이준호',
    follow_up_note: '다음 주 금요일까지 완료 예정',
    is_deleted: false,
  },
  {
    id: id(6),
    title: '고객사 API 연동 문서 업데이트',
    description: 'v2 API 변경사항 반영 및 예제 코드 추가.',
    priority: '높음',
    status: '진행중',
    source: 'notion',
    requester: '정하윤',
    requested_at: daysAgo(3),
    created_at: daysAgo(3),
    deadline: daysAgo(-1),
    started_at: daysAgo(1),
    completed_at: null,
    actual_duration: 120,
    is_duration_manual: false,
    notion_task_id: 'notion-page-002',
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: null,
    follow_up_note: null,
    is_deleted: false,
  },
  {
    id: id(7),
    title: '사내 해커톤 발표자료 준비',
    description: null,
    priority: '낮음',
    status: '보류',
    source: 'manual',
    requester: null,
    requested_at: null,
    created_at: daysAgo(5),
    deadline: daysAgo(-10),
    started_at: null,
    completed_at: null,
    actual_duration: null,
    is_duration_manual: false,
    notion_task_id: null,
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: null,
    follow_up_note: null,
    is_deleted: false,
  },
  {
    id: id(8),
    title: '모바일 앱 푸시 알림 버그 수정',
    description: 'iOS에서 백그라운드 알림이 오지 않는 이슈.',
    priority: '높음',
    status: '완료',
    source: 'slack',
    requester: '최유진',
    requested_at: daysAgo(1),
    created_at: daysAgo(1),
    deadline: daysAgo(0),
    started_at: daysAgo(1),
    completed_at: daysAgo(0),
    actual_duration: 180,
    is_duration_manual: false,
    notion_task_id: null,
    slack_url: 'https://slack.com/archives/C05678/p9876543210',
    notion_issue: null,
    slack_channel: 'mobile-bugs',
    slack_sender: '최유진',
    delegate_to: null,
    follow_up_note: null,
    is_deleted: false,
  },
  {
    id: id(9),
    title: '데이터베이스 인덱스 점검',
    description: '슬로우 쿼리 로그 분석 후 인덱스 추가/수정.',
    priority: '보통',
    status: '완료',
    source: 'manual',
    requester: null,
    requested_at: null,
    created_at: daysAgo(2),
    deadline: null,
    started_at: daysAgo(2),
    completed_at: daysAgo(1),
    actual_duration: 60,
    is_duration_manual: false,
    notion_task_id: null,
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: null,
    follow_up_note: null,
    is_deleted: false,
  },
  {
    id: id(10),
    title: '디자인 시스템 컬러 토큰 정리',
    description: '다크모드 대응을 위한 시맨틱 컬러 토큰 체계 수립.',
    priority: '보통',
    status: '취소',
    source: 'notion',
    requester: '김민지',
    requested_at: daysAgo(7),
    created_at: daysAgo(7),
    deadline: daysAgo(-3),
    started_at: null,
    completed_at: null,
    actual_duration: null,
    is_duration_manual: false,
    notion_task_id: 'notion-page-003',
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: null,
    follow_up_note: '디자인팀에서 직접 진행하기로 결정',
    is_deleted: false,
  },
  {
    id: id(11),
    title: '테스트 커버리지 80% 달성',
    description: '핵심 비즈니스 로직 단위 테스트 추가.',
    priority: '보통',
    status: '완료',
    source: 'manual',
    requester: null,
    requested_at: null,
    created_at: daysAgo(4),
    deadline: daysAgo(-1),
    started_at: daysAgo(3),
    completed_at: daysAgo(2),
    actual_duration: 240,
    is_duration_manual: false,
    notion_task_id: null,
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: null,
    follow_up_note: null,
    is_deleted: false,
  },
  {
    id: id(12),
    title: 'AWS 비용 최적화 리포트 작성',
    description: null,
    priority: '낮음',
    status: '완료',
    source: 'manual',
    requester: null,
    requested_at: null,
    created_at: daysAgo(6),
    deadline: null,
    started_at: daysAgo(5),
    completed_at: daysAgo(4),
    actual_duration: 90,
    is_duration_manual: true,
    notion_task_id: null,
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: null,
    follow_up_note: null,
    is_deleted: false,
  },
  // Deleted tasks (for trash page)
  {
    id: id(13),
    title: '레거시 API 마이그레이션 조사',
    description: '더 이상 필요하지 않은 태스크.',
    priority: '낮음',
    status: '대기',
    source: 'manual',
    requester: null,
    requested_at: null,
    created_at: daysAgo(10),
    deadline: null,
    started_at: null,
    completed_at: null,
    actual_duration: null,
    is_duration_manual: false,
    notion_task_id: null,
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: null,
    follow_up_note: null,
    is_deleted: true,
  },
  {
    id: id(14),
    title: '로그인 페이지 리디자인 (구버전)',
    description: '새 디자인으로 교체되어 삭제.',
    priority: '보통',
    status: '진행중',
    source: 'notion',
    requester: '김민지',
    requested_at: daysAgo(14),
    created_at: daysAgo(14),
    deadline: null,
    started_at: daysAgo(12),
    completed_at: null,
    actual_duration: 60,
    is_duration_manual: false,
    notion_task_id: 'notion-page-004',
    slack_url: null,
    notion_issue: null,
    slack_channel: null,
    slack_sender: null,
    delegate_to: null,
    follow_up_note: null,
    is_deleted: true,
  },
];

export const MOCK_TIMELOGS: TimeLog[] = [
  // Task 1 (진행중) - 3 sessions: 2 completed + 1 active (pause/resume pattern)
  { id: id(101), task_id: id(1), started_at: hoursAgo(6), ended_at: hoursAgo(5) },        // 세션 1: 1시간 (오전 작업)
  { id: id(110), task_id: id(1), started_at: hoursAgo(4), ended_at: hoursAgo(3.5) },      // 세션 2: 30분 (점심 후 재개)
  { id: id(111), task_id: id(1), started_at: hoursAgo(1), ended_at: null },                // 세션 3: 현재 진행중
  // Task 3 (완료) - 2 sessions
  { id: id(102), task_id: id(3), started_at: hoursAgo(4), ended_at: hoursAgo(3.5) },      // 30분
  { id: id(112), task_id: id(3), started_at: hoursAgo(2), ended_at: hoursAgo(1.75) },     // 15분
  // Task 4 (완료) - 2 hours in one session
  { id: id(103), task_id: id(4), started_at: hoursAgo(5), ended_at: hoursAgo(3) },
  // Task 6 - 3 sessions over 2 days (다른 일 하다가 돌아온 패턴)
  { id: id(104), task_id: id(6), started_at: new Date(new Date(daysAgo(1)).getTime() + 9 * 3600000).toISOString(), ended_at: new Date(new Date(daysAgo(1)).getTime() + 10 * 3600000).toISOString() },  // 어제 1시간
  { id: id(105), task_id: id(6), started_at: new Date(new Date(daysAgo(1)).getTime() + 14 * 3600000).toISOString(), ended_at: new Date(new Date(daysAgo(1)).getTime() + 14.5 * 3600000).toISOString() }, // 어제 30분
  { id: id(113), task_id: id(6), started_at: hoursAgo(3), ended_at: hoursAgo(2.5) },      // 오늘 30분
  // Task 8 - 3 hours over 2 sessions
  { id: id(106), task_id: id(8), started_at: new Date(new Date(daysAgo(1)).getTime() + 9 * 3600000).toISOString(), ended_at: new Date(new Date(daysAgo(1)).getTime() + 11 * 3600000).toISOString() },
  { id: id(107), task_id: id(8), started_at: new Date(new Date(daysAgo(0)).getTime() + 10 * 3600000).toISOString(), ended_at: new Date(new Date(daysAgo(0)).getTime() + 11 * 3600000).toISOString() },
  // Task 9
  { id: id(108), task_id: id(9), started_at: new Date(new Date(daysAgo(2)).getTime() + 14 * 3600000).toISOString(), ended_at: new Date(new Date(daysAgo(2)).getTime() + 15 * 3600000).toISOString() },
  // Task 11 - long sessions over multiple days
  { id: id(109), task_id: id(11), started_at: new Date(new Date(daysAgo(3)).getTime() + 9 * 3600000).toISOString(), ended_at: new Date(new Date(daysAgo(3)).getTime() + 13 * 3600000).toISOString() },
];

export const MOCK_CUSTOM_STATUSES: CustomStatus[] = [
  { id: id(201), name: '코드리뷰', color: '#8B5CF6', created_at: daysAgo(30) },
  { id: id(202), name: 'QA대기', color: '#EC4899', created_at: daysAgo(30) },
  { id: id(203), name: '배포예정', color: '#14B8A6', created_at: daysAgo(30) },
];

export const MOCK_NOTION_MAPPINGS: NotionStatusMapping[] = [
  { id: id(301), notion_status: 'Not Started', wid_status: '대기' },
  { id: id(302), notion_status: 'In Progress', wid_status: '진행중' },
  { id: id(303), notion_status: 'Done', wid_status: '완료' },
  { id: id(304), notion_status: 'Blocked', wid_status: '보류' },
];

// Helper: check if using mock data
export function isMockMode(): boolean {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  return !url || url === 'your-supabase-url' || url === '';
}
